### ISSUE TITLE
Sample players always overspend

### ISSUE THREAD

**Issue by mrakgr** [EssexUniversityMCTS/gvgai#10]
For some reason even the random player does that. Only the one step look ahead player seems to be doing anything.

It might be related to the way I opened the project in IntelliJ Idea. When importing from existing sources I only had the option to do so from Eclipse, Maven and Girdle - no Ant - so I created a new project. I noticed that the [uiDesigner.xml](https://github.com/EssexUniversityMCTS/gvgai/tree/master/.idea) file in the .idea folder got overwritten by that. Was that wrong? I am not too familiar with Java.

Edit: It might be related to this [thread](https://groups.google.com/forum/#!topic/the-general-video-game-competition/SLeFAIrDuEc).

For reference, I am running the VGV-AI library in Windows 10 from IdeaJ 15.

Edit2: Ah, I see that this is a [well known problem](https://groups.google.com/forum/#!topic/the-general-video-game-competition/1XVh3MWiddY). I managed to get around it by uncommenting disqualification in the MovingAvatar.java file. There was also suggested that can get around the issue by replacing CPU_TIME with WALL_TIME, but that is not in the aforementioned file. It is in the CompetitionParameters.java instead.

I've verified that the later fix works as well.

Might want to keep this issue around until it gets fixed.

**Comment by diegopliebana** [comment]
Dear mrakgr,

Many thanks for your report. I was actually going to suggest exactly that, quite possible the problem is the WALL/CPU time issue on Windows. Are you using that SO? If that's the case, I'd recommend you to switch to WALL_CPU time until we get this sorted.
