### ISSUE TITLE
DigDug's boulder type does not transform properly into the resting type

### ISSUE THREAD

**Issue by mrakgr** [EssexUniversityMCTS/gvgai#13]
If you shoot a boulder at a wall and then dig-remove the wall from the side, the boulder will continue moving. Also based on the interaction set, a supposed resting boulder should not be killing enemies, but here it clearly does, confirming again that it is not of resting type.

**Comment by diegopliebana** [comment]
Thanks! This has been fixed in the version 2.0 of our framework, which can be dowloaded here: http://www.gvgai.net/software.php

NOTE: The submission server is still running the previous version of VGDL, take this into account if you update your framework and intend to submit.
