### ISSUE TITLE
Make Pacman powerpills not look like fruit

### ISSUE THREAD

**Issue by mrakgr** [EssexUniversityMCTS/gvgai#14]
It helps to give hungry and powered their separate images. Sure enough, the avatar gets killed when trying to eat the ghosts no matter what it eats. This is from the mid January version of the library.

Update:

I am working off master now and am still getting the same problem. I am not sure why this is. Unlike before, now it sometimes works and sometime it does not.

**Comment by mrakgr** [comment]
Er, nevermind. I see that some of the power pills are fruit now. I do not remember that being in the original Pacman! :)

**Comment by mrakgr** [comment]
Actually, make those powerpills not look like fruit. I do not know who thought it was a good idea to troll the player like that.

**Comment by diegopliebana** [comment]
Hello,

We are working on updating the graphics of all games, and that obviously includes pacman. Therefore, this will be fixed with the new sprites.
