### ISSUE TITLE
Irrational behavior with default changeResource and collectResource values

### ISSUE THREAD

**Issue by mrakgr** [EssexUniversityMCTS/gvgai#15]
crew  > Resource color=GREEN limit=4 value=0 img=alien
    avatar diver > changeResource resource=crew

The above is from SeaQuest.

It took me a while to figure out why the crew resource is not being collected in my [own library](https://github.com/mrakgr/GVGAI-Fsharp). Logically, the above combination should lead to changeResource being changed by 0. The semantics of the above is rather poorly thought out.

I would guess that if I took a look into the library source, I would find a nested if that sets the value to 1 if both the value in changeResource and the sprite set is 0 (which it most likely is by default.)

If would be smarter to set the default values of both changeResource and the sprite set to 1 and then override that.

Update:

Let me just add that the semantics of SeaQuest are broken in general. As it is now, the game only works as intended if the avatar makes exactly 20x20 grid steps otherwise when the avatar dives up it can get 2000 points for a single save vs 1000 that were intended. The engine triggers two spawns of 'saved' if the avatar is across the grid boundaries.

The solution here would be to add changeResourceIfMore (and changeResourceIfLess while we are at it) instead of relying on the spawnIfMore+KillSprite combo.

**Comment by diegopliebana** [comment]
Thanks for your report. Comments below:

> If would be smarter to set the default values of both changeResource and the sprite set to 1 and then override that.

That is exactly the case! The default value for the parameter "value" in ChangeResource.java and in Resource.java is, in both, 1. So:
```
crew  > Resource color=GREEN limit=4 value=0 img=alien
avatar diver > changeResource resource=crew
```
adds one resource to the avatar. Or am I missing something?

> As it is now, the game only works as intended if the avatar makes exactly 20x20 grid steps otherwise when the avatar dives up it can get 2000 points for a single save vs 1000 that were intended. The engine triggers two spawns of 'saved' if the avatar is across the grid boundaries.

You are right! For the 2.0 version, we introduced a "spend" parameter to the SpawnIfHasMore effect, which spends the resource. Adding spend = 4 in this interaction solves the issue. It is fixed in the new version of the framework. The vgdl code for this now looks like this:

        avatar sky > addHealthPoints value=1
        avatar sky > spawnIfHasMore resource=crew stype=saved limit=4 spend=4
        saved  sky > killSprite scoreChange=1000


Thanks!

**Comment by mrakgr** [comment]
In the first case if `value=0` is defined in the Resource then why doesn't CollectResource add that zero value to the sprite it is being applied to? Shouldn't it override the default value? Though I'll admit that adding 0 would just be a waste of clock cycles, I do not understand why `value=0` is even there.

**Comment by diegopliebana** [comment]
Ok, got it, I see what you mean. In fact you're right, value=0 is superfluous in this game, and so does the collectResource interaction, in fact.

Only using:

avatar diver > changeResource resource=crew

with the default value=1 works and it's simpler. Changes have been made for 2.0.

Many thanks!

PS: I'll start with your suggestion issue next, when I find the time.
