### ISSUE TITLE
Remove the unnecessary value=0 in BoloAdventures game description

### ISSUE THREAD

**Issue by mrakgr** [EssexUniversityMCTS/gvgai#21]
In reference to [this issue](https://github.com/EssexUniversityMCTS/gvgai/issues/15), the `value=0` in `pushingbox > Resource limit=2 value=0` could be removed without changing the game semantics any.

The `value=0` in the SpriteSet causes complications as when the `changeResource value=1` it defaults to the object's value which is one causing it to not accumulate resource. This is not a problem in the old GVGAI library that I am working off, but it is in my own and it will be in the current one if the default of value is 1.

Doing it completely correctly would require introducing [optional types](https://en.wikipedia.org/wiki/Option_type) that I'd rather not do for efficiency's sake. Best to just amend the game description slightly in this case.

Edit:

It might be worth it to get rid of `value=0` in `chip > Resource img=gold limit=11 value=0` in ChipsChallenge as well.

`value=0` in `flippers > Resource img=diamond limit=1 value=0`, `fireboots > Resource img=powerpill limit=1 value=0` as well.

Edit2:

        prepainting > Resource limit=2 value=0
        pregrounding > Resource limit=2 value=0

There are `value=0`s in Painter as well.

**Comment by diegopliebana** [comment]
BoloAdventures - pushinbox does not exist any more (game definition changed).
ChipsChallenge - Done
Painter - Done.
