### ISSUE TITLE
Remove tab from the Painter game description

### ISSUE THREAD

**Issue by mrakgr** [EssexUniversityMCTS/gvgai#22]
prepaint avatar > killSprite
       	    ground avatar > spawnIfHasMore stype=prepaint resource=null limit=0
        prepaint ground > changeResource resource=prepainting value=1

This one is really hard to see, and in fact the IDE will show it properly, but there is a horizontal tab just before `ground` exactly 1 space long. I have no idea why it is only 1 space long. Some of the other game descriptions had tabs with 4 spaces, but this one threw me for a loop. I had to do a char by char comparison to figure it out.

**Comment by diegopliebana** [comment]
Fixed.

**Comment by mrakgr** [comment]
Thanks. I am surprised that the parser for GVGAI manages to parse it correctly here.
