### ISSUE TITLE
When running the sample geneticGenerator, it complains of a missing nil.txt file

### ISSUE THREAD

**Issue by chongdashu** [EssexUniversityMCTS/gvgai#24]
Reproduction steps:
 + Go to `src/Test.java`
 + Uncomment out the lines that will generate and play on generated level
 + Make sure that the `geneticGenerator` is placed in as the argument to the `ArcadeMachine.generateOneLevel` method.
 + Run the program.

Outcome:
+ Throws a `FIleNotFoundException` because of a missing `nil.txt` file.

**Comment by diegopliebana** [comment]
Is this fixed? can I close it?

**Comment by anadrome** [comment]
Yes, this was fixed in c69ec068122e93650c229e3c30fac1bab54363ca, the contents of the nil.txt file were changed into static data.

**Comment by diegopliebana** [comment]
Great, thanks!

**Comment by chongdashu** [comment]
Yes, that's right. Sorry about my delay in getting back to this!

**Comment by diegopliebana** [comment]
Nothing to worry about! Thanks :)
