### ISSUE TITLE
Inactive rules due to referencing undeclared sprites

### ISSUE THREAD

**Issue by anadrome** [EssexUniversityMCTS/gvgai#28]
After noticing a typo that made a rule inactive in 687827dfc69ac886c9b5b9d7e02c609888fdde71, I wondered if there were any others, so wrote a quick Perl script to check. I found two more, but I'm not 100% sure what the fix is for these two, since unlike that case, these aren't obvious typos.

In chipschallenge.txt, the sprite `keyused` isn't defined, in rule:

`keyused avatar > killSprite`

In lemmings.txt, the sprite `boulder` isn't defined, in rule:

`boulder wall > stepBack`

**Comment by diegopliebana** [comment]
Thanks! This is fixed (the solution was to simply remove those interactions, as they were ignored).
