### ISSUE TITLE
Parser warning with the 'surround' game

### ISSUE THREAD

**Issue by anadrome** [EssexUniversityMCTS/gvgai#32]
```Unknown field (frame_rate=30) from BasicGame frame_rate=30 square_size=30```

There is actually a field named frame_rate in the Game base class, but the parser doesn't like something about this.

**Comment by diegopliebana** [comment]
The real issue is that the field in Game is not public, hence reflection can't find it. But the point is that this variable is not even used, so I'll just simply remove it from code and game.
Thanks!
