### ISSUE TITLE
Reference functions don't work

### ISSUE THREAD

**Issue by amidos2006** [EssexUniversityMCTS/gvgai#39]
I was calling getPortalPositions from the state object using the player position. 

The result is the same if I didn't send the player position. It doesn't get reference position, I had to do it by myself.

**Comment by diegopliebana** [comment]
Hi Ahmed,

Which branch did you find this issue in?

Thanks!

**Comment by amidos2006** [comment]
The master branch :D I don’t know if u fixed it or not before, but it was a code downloaded by my friend “ivan”  2 month ago.

**Comment by diegopliebana** [comment]
Ok, thanks, looking into it now. I checked with Escape, and all seems normal. Which game and level did you use?

**Comment by amidos2006** [comment]
CamelRace, level 0

**Comment by diegopliebana** [comment]
This is what I see if I run in CamelRace level0, from the initial state. They are sorted in the second case, aren't they? 

<img width="611" alt="camelrace_portals" src="https://cloud.githubusercontent.com/assets/2753715/14769171/d5d8089e-0a4a-11e6-9dbf-91242c5d346e.png">

**Comment by amidos2006** [comment]
so it just sort them, it doesn't give the reference position between playerPosition and objPosition (objPosition - playerPosition) :D my bad :) I thought it suppose to return reference position

This is my bad :)

**Comment by diegopliebana** [comment]
Ahh! No, not at all :)

It can easily be obtained, using observation.position, but it doesn't calculate that internally.

No worries ;)
