### ISSUE TITLE
Conflicts of termination conditions

### ISSUE THREAD

**Issue by muupan** [EssexUniversityMCTS/gvgai#83]
It's not clear what happens if multiple termination conditions are satisfied simultaneously from the wiki. https://github.com/EssexUniversityMCTS/gvgai/wiki/Termination-Conditions

**Comment by rdgain** [comment]
Hi! 

I have added a clarification on this. The entirety of the VGDL language is sequential, all interactions and terminations are checked one at a time, from top to bottom. Therefore, if more than one termination condition is satisfied, the first one would trigger.

I hope this helps!
Raluca.

**Comment by muupan** [comment]
thank you!
