### ISSUE TITLE
The avatar can reach the goal, scoring 1.0, still losing a game in labyrinth

### ISSUE THREAD

**Issue by muupan** [EssexUniversityMCTS/gvgai#84]
In `examples/gridphysics/labyrinth.txt`, if the avatar takes an action at gameTick=1000 and reaches the goal, its score will be 1.0, but it will lose a game. Is it an expected behavior?

**Comment by diegopliebana** [comment]
Thanks! No, this is not correct. It's been fixed in the game now.

**Comment by muupan** [comment]
thank you!
