### ISSUE TITLE
Training phase not being terminated with Python client (Single Player Learning Track)

### ISSUE THREAD

**Issue by ercumentilhan** [EssexUniversityMCTS/gvgai#87]
The **Single Player Learning Track** instructions state the following:

> In case that 5 minutes has been used up, the results and observation of the game will still be sent to the agent and the agent will have no more than 1 second before the validation.

However, I had an issue of training phase not being terminated at all in the case of Python client with socket communication where the result is handled as follows (in _gvgai/clients/GVGAI-PythonClient/src/utils/ClientComm.py_):

```
 def result(self):
        ect = ElapsedCpuTimer()

        if not self.global_ect.exceededMaxTime():
            ect = self.global_ect.copy()
        else:
            ect.setMaxTimeMillis(CompetitionParameters.EXTRA_LEARNING_TIME)

        nextLevel = self.player.result(self.sso, ect.copy())

        if ect.exceededMaxTime():
            self.io.writeToServer(self.lastMessageId, "END_OVERSPENT", self.LOG)
        else:
            self.io.writeToServer(self.lastMessageId, str(nextLevel), self.LOG)
```

Modifying the function in a way to make it post _END_TRAINING_ message to the server if `self.global_ect.exceededMaxTime()` is `True` solves this problem. 

Is this a bug or a behavior related to a misuse on my side?

**Comment by diegopliebana** [comment]
You're right, this was a bug. It's now been fixed and committed. 

Thanks!
Diego.
