### ISSUE TITLE
Misnamed variable in SerializableStateObservation.py

### ISSUE THREAD

**Issue by ercumentilhan** [EssexUniversityMCTS/gvgai#97]
In `gvgai/clients/GVGAI-PythonClient/src/utils/SerializableStateObservation.py` file, the variable `self.fromAvatarSpritePositions = []` in line 54 seems to be misnamed. This does not give an error but the corresponding list always remains empty.

Changing it into `self.fromAvatarSpritesPositions = []` resolved the issue for me.

**Comment by dvionit** [comment]
Hello,

The field did indeed have the name misspelled on the latest version.
Thank you for notifying. It has been fixed.

Closed.
