### ISSUE TITLE
A problem with the position lists in SerializableStateObservation (Python client)

### ISSUE THREAD

**Issue by ercumentilhan** [EssexUniversityMCTS/gvgai#98]
`SerializableStateObservation` object in the Python client seem to hold wrong information in some of the observation lists such as `fromAvatarSpritesPositions`.

For example, in the game 0 (Aliens), size of the `fromAvatarSpritesPositions` in `SerializableStateObservation`s you receive at every game step is 0 until you shoot a missile, then it becomes 1 (no problem until here). However, even after the missile leaves the game, the size of the list remains 1 (with a fixed, wrong(?) position) just as if there is an actual missile present in the game.

There may be a problem unless I am missing something.

**Comment by ercumentilhan** [comment]
Executing `self.sso = SerializableStateObservation()` line every time a valid message is received in `processLine(self, msg)` function of `ClientComm.py` seem to resolve this issue.

**Comment by ljialin** [comment]
Thank you! This is fixed according to your comment.
